name: Notes Application CI Pipeline
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      
      - name: Install dependencies
        run: |
          echo Installing dependencies
          npm install --prefix src
      
      - name: Run MongoDB Docker Container
        run: docker-compose up -d
      
      - name: Perform Lint Testing
        run: npm run test-lint --prefix src
        continue-on-error: false
      
      - name: Create log file
        if: failure()
        run: |
          echo "Workflow Failure Log" > failure.log
          echo "---------------------------" >> failure.log
          echo "Date & Time of Failure: $(date)" >> failure.log
          echo "Job: '${{ github.job }}'" >> failure.log
          echo "Step: '${{ github.step }}'" >> failure.log
          echo "Error message: '${{ job.message }}'" >> failure.log
      - name: Upload log file
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: failure-log
          path: failure.log

